services:
  - type: web
    name: nvc-backend
    env: node
    plan: free
    region: frankfurt        # One of the two free-supported regions
    buildCommand: "npm install"
    startCommand: "node app.js"
    autoDeploy: true

    envVars:
      NODE_ENV: production
